name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # First install with npm ci (fast, locked dependencies)
      - name: Install dependencies (ci)
        run: npm ci

      # Then optionally run npm install (if you need updates)
      - name: Install dependencies (install)
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
